// Generated by gencpp from file hello_test/LocalizePartRequest.msg
// DO NOT EDIT!


#ifndef HELLO_TEST_MESSAGE_LOCALIZEPARTREQUEST_H
#define HELLO_TEST_MESSAGE_LOCALIZEPARTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hello_test
{
template <class ContainerAllocator>
struct LocalizePartRequest_
{
  typedef LocalizePartRequest_<ContainerAllocator> Type;

  LocalizePartRequest_()
    : base_frame()  {
    }
  LocalizePartRequest_(const ContainerAllocator& _alloc)
    : base_frame(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _base_frame_type;
  _base_frame_type base_frame;




  typedef boost::shared_ptr< ::hello_test::LocalizePartRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hello_test::LocalizePartRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LocalizePartRequest_

typedef ::hello_test::LocalizePartRequest_<std::allocator<void> > LocalizePartRequest;

typedef boost::shared_ptr< ::hello_test::LocalizePartRequest > LocalizePartRequestPtr;
typedef boost::shared_ptr< ::hello_test::LocalizePartRequest const> LocalizePartRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hello_test::LocalizePartRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hello_test::LocalizePartRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hello_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hello_test::LocalizePartRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hello_test::LocalizePartRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_test::LocalizePartRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hello_test::LocalizePartRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_test::LocalizePartRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hello_test::LocalizePartRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hello_test::LocalizePartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5742700117844b07d72df47ca3da17d";
  }

  static const char* value(const ::hello_test::LocalizePartRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5742700117844b0ULL;
  static const uint64_t static_value2 = 0x7d72df47ca3da17dULL;
};

template<class ContainerAllocator>
struct DataType< ::hello_test::LocalizePartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hello_test/LocalizePartRequest";
  }

  static const char* value(const ::hello_test::LocalizePartRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hello_test::LocalizePartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string base_frame\n\
";
  }

  static const char* value(const ::hello_test::LocalizePartRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hello_test::LocalizePartRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.base_frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocalizePartRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hello_test::LocalizePartRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hello_test::LocalizePartRequest_<ContainerAllocator>& v)
  {
    s << indent << "base_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.base_frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HELLO_TEST_MESSAGE_LOCALIZEPARTREQUEST_H
