// Generated by gencpp from file hello_test/LocalizePart.msg
// DO NOT EDIT!


#ifndef HELLO_TEST_MESSAGE_LOCALIZEPART_H
#define HELLO_TEST_MESSAGE_LOCALIZEPART_H

#include <ros/service_traits.h>


#include <hello_test/LocalizePartRequest.h>
#include <hello_test/LocalizePartResponse.h>


namespace hello_test
{

struct LocalizePart
{

typedef LocalizePartRequest Request;
typedef LocalizePartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LocalizePart
} // namespace hello_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hello_test::LocalizePart > {
  static const char* value()
  {
    return "aa4cca5b67ec8a13449c405ec10ee5d0";
  }

  static const char* value(const ::hello_test::LocalizePart&) { return value(); }
};

template<>
struct DataType< ::hello_test::LocalizePart > {
  static const char* value()
  {
    return "hello_test/LocalizePart";
  }

  static const char* value(const ::hello_test::LocalizePart&) { return value(); }
};


// service_traits::MD5Sum< ::hello_test::LocalizePartRequest> should match 
// service_traits::MD5Sum< ::hello_test::LocalizePart > 
template<>
struct MD5Sum< ::hello_test::LocalizePartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hello_test::LocalizePart >::value();
  }
  static const char* value(const ::hello_test::LocalizePartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_test::LocalizePartRequest> should match 
// service_traits::DataType< ::hello_test::LocalizePart > 
template<>
struct DataType< ::hello_test::LocalizePartRequest>
{
  static const char* value()
  {
    return DataType< ::hello_test::LocalizePart >::value();
  }
  static const char* value(const ::hello_test::LocalizePartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hello_test::LocalizePartResponse> should match 
// service_traits::MD5Sum< ::hello_test::LocalizePart > 
template<>
struct MD5Sum< ::hello_test::LocalizePartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hello_test::LocalizePart >::value();
  }
  static const char* value(const ::hello_test::LocalizePartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_test::LocalizePartResponse> should match 
// service_traits::DataType< ::hello_test::LocalizePart > 
template<>
struct DataType< ::hello_test::LocalizePartResponse>
{
  static const char* value()
  {
    return DataType< ::hello_test::LocalizePart >::value();
  }
  static const char* value(const ::hello_test::LocalizePartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HELLO_TEST_MESSAGE_LOCALIZEPART_H
